/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef _MGMHistEfficiency_hh_
#define _MGMHistEfficiency_hh_

#include "RooAbsReal.h"
#include "RooRealProxy.h"
class TH1;
class RooRealVar;
 
class MGMHistEfficiency : public RooAbsReal {
public:
  MGMHistEfficiency() {} ; 
  MGMHistEfficiency(const char *name, const char *title,
	               const RooRealVar& _depVar,
	               RooAbsReal& _offset,
	               RooAbsReal& _slope,
	               TH1&  _ahist);
  MGMHistEfficiency(const MGMHistEfficiency& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MGMHistEfficiency(*this,newname); }
  inline virtual ~MGMHistEfficiency() { }

protected:

  RooRealProxy fOffset;
  RooRealProxy fSlope;
  TH1*         fHist;
  Double_t     fLowerLimit;
  
  Double_t evaluate() const ;

private:

  ClassDef(MGMHistEfficiency,1) // Your description goes here...
};
 
#endif
