 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "MGMHistEfficiency.hh" 
 #include "RooRealVar.h" 
 #include "TH1.h" 

 ClassImp(MGMHistEfficiency) 

 MGMHistEfficiency::MGMHistEfficiency(const char *name, const char *title,
	              const RooRealVar& _depVar,
	              RooAbsReal& _offset,
	              RooAbsReal& _slope,
	              TH1&  _ahist) :
   RooAbsReal(name,title), 
   fOffset("fOffset","fOffset",this,_offset),
   fSlope("fSlope","fSlope",this,_slope),
   fHist(&_ahist),
   fLowerLimit(_depVar.getMin())
 { 
 } 


 MGMHistEfficiency::MGMHistEfficiency(const MGMHistEfficiency& other, const char* name) :  
   RooAbsReal(other, name), 
   fOffset("fOffset",this,other.fOffset),
   fSlope("fSlope",this,other.fSlope),
   fHist(other.fHist),
   fLowerLimit(other.fLowerLimit)
 { 
 } 



 Double_t MGMHistEfficiency::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t minEnergy = fLowerLimit*fSlope + fOffset;
   return fHist->Interpolate(minEnergy); 
 } 



