/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef _MGMPiecewiseFunction_hh_
#define _MGMPiecewiseFunction_hh_

#include "RooRealProxy.h"
#include "RooAbsPdf.h"

class MGMPiecewiseRegions;
class MGMPiecewiseFunction : public RooAbsPdf {
public:
  MGMPiecewiseFunction() {} ; 
  MGMPiecewiseFunction(const char *name, const char *title,
	      RooAbsReal& _var);
  MGMPiecewiseFunction(const MGMPiecewiseFunction& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MGMPiecewiseFunction(*this,newname); }
  inline virtual ~MGMPiecewiseFunction() { }

  void SetRegionsOfValidity(const MGMPiecewiseRegions* reg) { fRegions = reg; }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName) const;
protected:

  RooRealProxy fVariable ;
  const MGMPiecewiseRegions* fRegions;
  
  Double_t evaluate() const ;

private:

  ClassDef(MGMPiecewiseFunction,1) // Your description goes here...
};
 
#endif
